<?php
/**
 * Renders prompt-test results as markdown.
 *
 * The report is rewritten in full after every prompt rather than once at the
 * end. It is a small file, and a full rewrite is the only thing that survives
 * the failure mode a try/catch cannot reach: a PHP fatal, an OOM kill or a
 * ctrl-C thirty prompts into a paid run still leaves a readable report of the
 * thirty that finished.
 *
 * @package    Agent_Builder
 * @subpackage Prompt_Testing
 * @since      3.4.1
 *
 * php version 8.1
 */

declare( strict_types=1 );

namespace Agentic\Prompt_Testing;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Builds the prompt_test_results.md document.
 */
final class Prompt_Test_Reporter {

	/**
	 * Run metadata for the header.
	 *
	 * @var array<string, mixed>
	 */
	private array $meta;

	/**
	 * Render options.
	 *
	 * @var array<string, mixed>
	 */
	private array $options;

	/**
	 * Constructor.
	 *
	 * @param array<string, mixed> $meta    Run metadata.
	 * @param array<string, mixed> $options Render options.
	 */
	public function __construct( array $meta, array $options = array() ) {
		$this->meta    = $meta;
		$this->options = wp_parse_args(
			$options,
			array(
				'max_response_chars' => 2000,
			)
		);
	}

	/**
	 * Write the report to disk.
	 *
	 * @param array<int, array<string, mixed>> $records Result records.
	 * @param array<string, float|int>         $totals  Running totals.
	 * @param string                           $path    Destination path.
	 * @return bool
	 */
	public function flush( array $records, array $totals, string $path ): bool {
		$dir = dirname( $path );

		if ( ! is_dir( $dir ) ) {
			wp_mkdir_p( $dir );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Local report file; WP_Filesystem is not initialised in a CLI context.
		return false !== file_put_contents( $path, $this->render( $records, $totals ) );
	}

	/**
	 * Render the whole report.
	 *
	 * @param array<int, array<string, mixed>> $records Result records.
	 * @param array<string, float|int>         $totals  Running totals.
	 * @return string
	 */
	public function render( array $records, array $totals ): string {
		// Sections, not lines — each renders its own internal spacing, and the
		// only thing filtered out is a section that produced nothing at all (the
		// failures index when everything passed). Filtering at line level would
		// also eat the blank lines markdown needs between blocks.
		$sections = array(
			"# Agent Builder — Prompt Test Results\n",
			"> Generated by `wp agent prompt-test`. Overwritten on every run, and gitignored.\n"
				. '> These are real LLM calls against a live WordPress install.',
			$this->render_header( $totals ),
			$this->render_summary_table( $records ),
			$this->render_failures_index( $records ),
			'## Details',
		);

		foreach ( $records as $record ) {
			$sections[] = $this->render_detail( $record );
		}

		$sections = array_map(
			static fn( string $section ): string => trim( $section, "\n" ),
			array_filter( $sections, static fn( string $section ): bool => '' !== trim( $section ) )
		);

		return implode( "\n\n", $sections ) . "\n";
	}

	/**
	 * The run header block.
	 *
	 * @param array<string, float|int> $totals Running totals.
	 * @return string
	 */
	private function render_header( array $totals ): string {
		$rows = array(
			'Run'              => gmdate( 'Y-m-d H:i:s' ) . ' UTC',
			'Plugin'           => (string) ( $this->meta['plugin_version'] ?? '' ),
			'WordPress'        => (string) ( $this->meta['wp_version'] ?? '' ),
			'PHP'              => (string) ( $this->meta['php_version'] ?? '' ),
			'Site'             => (string) ( $this->meta['site_url'] ?? '' ),
			'Provider / model' => sprintf( '%s / %s', $this->meta['provider'] ?? '?', $this->meta['model'] ?? '?' ),
			'Agent mode'       => (string) ( $this->meta['agent_mode'] ?? '' ),
			'Run as'           => (string) ( $this->meta['user'] ?? '' ),
			'Execution mode'   => (string) ( $this->meta['mode'] ?? 'chat' ),
			'Verdict mode'     => (string) ( $this->meta['verdict'] ?? 'assert' ),
			'Judge'            => empty( $this->meta['judge'] ) ? 'off' : 'on',
			'Response cache'   => 'bypassed for this run',
			'Catalog'          => (string) ( $this->meta['catalog'] ?? '' ),
			'Command'          => '`' . ( $this->meta['command'] ?? 'wp agent prompt-test' ) . '`',
		);

		$lines = array( '| | |', '|---|---|' );

		foreach ( $rows as $label => $value ) {
			if ( '' === trim( (string) $value ) ) {
				continue;
			}
			$lines[] = sprintf( '| %s | %s |', $label, $this->cell( (string) $value ) );
		}

		$summary = sprintf(
			'**%d run · %d passed · %d failed · %d skipped · %d errored · %d gated · %s tokens · $%s · %s**',
			(int) $totals['run'],
			(int) $totals['pass'],
			(int) $totals['fail'],
			(int) $totals['skip'],
			(int) $totals['error'],
			(int) $totals['gated'],
			number_format( (int) $totals['tokens'] ),
			number_format( (float) $totals['cost'], 4 ),
			$this->duration( (float) $totals['duration_ms'] )
		);

		$lines[] = '';
		$lines[] = $summary;

		if ( (int) $totals['judge_tokens'] > 0 ) {
			$lines[] = '';
			$lines[] = sprintf(
				'Judge (not counted above): %s tokens · $%s',
				number_format( (int) $totals['judge_tokens'] ),
				number_format( (float) $totals['judge_cost'], 4 )
			);
		}

		if ( (int) $totals['not_run'] > 0 ) {
			$lines[] = '';
			$lines[] = sprintf( '⚠️ %d prompt(s) were not run — the cost cap stopped the run early.', (int) $totals['not_run'] );
		}

		$lines[] = '';

		return implode( "\n", $lines );
	}

	/**
	 * The one-row-per-prompt summary table.
	 *
	 * @param array<int, array<string, mixed>> $records Result records.
	 * @return string
	 */
	private function render_summary_table( array $records ): string {
		$lines = array(
			'## Summary',
			'',
			'| ID | Rank | Agent | Answered by | Verdict | Tools | Iter | Tokens | Cost | Time |',
			'|---|---|---|---|---|---|---|---|---|---|',
		);

		foreach ( $records as $record ) {
			$answered = (string) $record['actual_agent'];

			$lines[] = sprintf(
				'| %s | %s | `%s` | %s | %s | %s | %s | %s | %s | %s |',
				$record['id'],
				$record['rank'] > 0 ? $record['rank'] : '—',
				$record['assigned_agent'],
				'' === $answered || $answered === $record['assigned_agent'] ? '—' : '`' . $answered . '`',
				$this->badge( $record ),
				empty( $record['tools_used'] ) ? '—' : $this->cell( implode( ', ', $record['tools_used'] ) ),
				$record['iterations'] > 0 ? $record['iterations'] : '—',
				$record['tokens'] > 0 ? number_format( (int) $record['tokens'] ) : '—',
				$record['cost'] > 0 ? '$' . number_format( (float) $record['cost'], 4 ) : '—',
				$record['duration_ms'] > 0 ? $this->duration( (float) $record['duration_ms'] ) : '—'
			);
		}

		$lines[] = '';

		return implode( "\n", $lines );
	}

	/**
	 * A quick index of everything that did not pass.
	 *
	 * @param array<int, array<string, mixed>> $records Result records.
	 * @return string
	 */
	private function render_failures_index( array $records ): string {
		$problems = array_filter(
			$records,
			static fn( array $r ): bool => in_array(
				$r['verdict'],
				array( Prompt_Test_Runner::VERDICT_FAIL, Prompt_Test_Runner::VERDICT_ERROR, Prompt_Test_Runner::VERDICT_SKIP ),
				true
			)
		);

		if ( empty( $problems ) ) {
			return '';
		}

		$lines = array( '## Needs attention', '' );

		foreach ( $problems as $record ) {
			$lines[] = sprintf(
				'- **%s** (`%s`) — %s: %s',
				$record['id'],
				$record['assigned_agent'],
				$record['verdict'],
				implode( '; ', (array) $record['verdict_reasons'] )
			);
		}

		$lines[] = '';

		return implode( "\n", $lines );
	}

	/**
	 * One prompt's detail section.
	 *
	 * @param array<string, mixed> $record Result record.
	 * @return string
	 */
	private function render_detail( array $record ): string {
		$lines = array(
			sprintf(
				'### %s · rank %s · `%s` — %s',
				$record['id'],
				$record['rank'] > 0 ? $record['rank'] : '—',
				$record['assigned_agent'],
				$this->badge( $record )
			),
			'',
			'**Prompt**',
			'',
			'> ' . str_replace( "\n", "\n> ", (string) $record['prompt'] ),
			'',
		);

		if ( ! empty( $record['verdict_reasons'] ) ) {
			$lines[] = '**Why**';
			$lines[] = '';
			foreach ( (array) $record['verdict_reasons'] as $reason ) {
				$lines[] = '- ' . $reason;
			}
			$lines[] = '';
		}

		$facts = array();

		if ( ! empty( $record['expect_tools'] ) ) {
			$facts[] = sprintf( '**Expected tools:** `%s`', implode( '`, `', (array) $record['expect_tools'] ) );
		}

		if ( ! empty( $record['tools_used'] ) ) {
			$facts[] = sprintf( '**Called:** `%s`', implode( '`, `', (array) $record['tools_used'] ) );
		}

		if ( ! empty( $record['delegated_to'] ) ) {
			$facts[] = sprintf( '**Delegated to:** %s', implode( ', ', (array) $record['delegated_to'] ) );
		}

		if ( $record['tokens'] > 0 || $record['duration_ms'] > 0 ) {
			$facts[] = sprintf(
				'**Iterations:** %d · **Tokens:** %s · **Cost:** $%s · **Duration:** %s',
				(int) $record['iterations'],
				number_format( (int) $record['tokens'] ),
				number_format( (float) $record['cost'], 4 ),
				$this->duration( (float) $record['duration_ms'] )
			);
		}

		if ( ! empty( $record['judge_score'] ) || '' !== (string) $record['judge_comment'] ) {
			$facts[] = sprintf(
				'**Judge:** %s — %s',
				$record['judge_score'] > 0 ? $record['judge_score'] . '/5' : 'no score',
				$record['judge_comment']
			);
		}

		if ( ! empty( $record['gated'] ) ) {
			$facts[] = sprintf(
				'**Risk gate:** %s%s — this is the safety model working, not a failure.',
				'' === (string) $record['approval_kind'] ? 'stopped for approval' : $record['approval_kind'],
				'' === (string) $record['approval_detail'] ? '' : ' (' . $record['approval_detail'] . ')'
			);
		}

		if ( '' !== (string) $record['notes'] ) {
			$facts[] = sprintf( '**Catalog notes:** %s', $record['notes'] );
		}

		if ( ! empty( $facts ) ) {
			$lines[] = implode( "  \n", $facts );
			$lines[] = '';
		}

		if ( '' !== (string) $record['error_location'] ) {
			$lines[] = sprintf( '**Threw:** `%s` at `%s`', $record['error_class'], $record['error_location'] );
			$lines[] = '';
			$lines[] = $this->details( 'Stack trace', $this->fence( (string) $record['error_trace'] ) );
			$lines[] = '';
		}

		$response = (string) $record['response'];

		if ( '' !== trim( $response ) ) {
			$max       = (int) $this->options['max_response_chars'];
			$truncated = $max > 0 && mb_strlen( $response ) > $max;
			$shown     = $truncated ? mb_substr( $response, 0, $max ) . "\n…" : $response;

			$summary = sprintf(
				'Response (%s chars%s)',
				number_format( (int) $record['response_length'] ),
				$truncated ? sprintf( ', showing first %s', number_format( $max ) ) : ''
			);

			$lines[] = $this->details( $summary, $this->fence( $shown ) );
			$lines[] = '';
		}

		if ( '' !== trim( (string) $record['reasoning'] ) ) {
			$lines[] = $this->details( 'Reasoning', $this->fence( (string) $record['reasoning'] ) );
			$lines[] = '';
		}

		return implode( "\n", $lines );
	}

	/**
	 * Wrap content in a collapsible block.
	 *
	 * A fifty-entry report with every response expanded is unreadable; collapsed,
	 * it fits on a screen and still holds everything.
	 *
	 * @param string $summary Summary line.
	 * @param string $content Body.
	 * @return string
	 */
	private function details( string $summary, string $content ): string {
		return sprintf( "<details><summary>%s</summary>\n\n%s\n\n</details>", $summary, $content );
	}

	/**
	 * Fence arbitrary content safely.
	 *
	 * LLM answers routinely contain triple-backtick code blocks of their own, so
	 * the outer fence has to be longer than the longest run inside.
	 *
	 * @param string $content Content to fence.
	 * @return string
	 */
	private function fence( string $content ): string {
		$runs   = array();
		$length = 3;

		if ( preg_match_all( '/`+/', $content, $runs ) ) {
			foreach ( $runs[0] as $run ) {
				$length = max( $length, strlen( $run ) + 1 );
			}
		}

		$fence = str_repeat( '`', $length );

		return $fence . "\n" . $content . "\n" . $fence;
	}

	/**
	 * Make a value safe to drop into a markdown table cell.
	 *
	 * @param string $value Raw value.
	 * @return string
	 */
	private function cell( string $value ): string {
		$value = str_replace( '|', '\\|', $value );
		$value = (string) preg_replace( '/\R/', '<br>', $value );

		return trim( $value );
	}

	/**
	 * The verdict badge for a record.
	 *
	 * @param array<string, mixed> $record Result record.
	 * @return string
	 */
	private function badge( array $record ): string {
		$verdict = (string) $record['verdict'];

		$icon = match ( $verdict ) {
			Prompt_Test_Runner::VERDICT_PASS    => '✅',
			Prompt_Test_Runner::VERDICT_FAIL    => '❌',
			Prompt_Test_Runner::VERDICT_ERROR   => '💥',
			Prompt_Test_Runner::VERDICT_SKIP    => '⏭',
			Prompt_Test_Runner::VERDICT_NOT_RUN => '⏹',
			default                             => 'ℹ️',
		};

		$badge = $icon . ' ' . $verdict;

		if ( ! empty( $record['gated'] ) ) {
			$badge .= ' ⏸';
		}

		if ( ! empty( $record['judge_score'] ) ) {
			$badge .= sprintf( ' (%d/5)', (int) $record['judge_score'] );
		}

		return $badge;
	}

	/**
	 * Human-readable duration.
	 *
	 * @param float $ms Milliseconds.
	 * @return string
	 */
	private function duration( float $ms ): string {
		if ( $ms < 1000 ) {
			return sprintf( '%dms', (int) round( $ms ) );
		}

		$seconds = $ms / 1000;

		if ( $seconds < 60 ) {
			return sprintf( '%.1fs', $seconds );
		}

		return sprintf( '%dm %ds', (int) floor( $seconds / 60 ), (int) round( fmod( $seconds, 60 ) ) );
	}

	/**
	 * Flatten records for --format=table/json/csv output.
	 *
	 * @param array<int, array<string, mixed>> $records Result records.
	 * @return array<int, array<string, mixed>>
	 */
	public function to_rows( array $records ): array {
		return array_map(
			static fn( array $r ): array => array(
				'id'      => $r['id'],
				'rank'    => $r['rank'],
				'agent'   => $r['assigned_agent'],
				'verdict' => $r['verdict'] . ( empty( $r['gated'] ) ? '' : ' (gated)' ),
				'tools'   => implode( ' ', (array) $r['tools_used'] ),
				'tokens'  => $r['tokens'],
				'cost'    => round( (float) $r['cost'], 4 ),
				'ms'      => $r['duration_ms'],
				'judge'   => $r['judge_score'],
				'reasons' => implode( '; ', (array) $r['verdict_reasons'] ),
			),
			$records
		);
	}
}
